### ISSUE TITLE
6.7 Βελτίωση πρότασης maven-assembly-plugin

### ISSUE THREAD

**Issue by skarmoutsosv** [jkost/jkost.github.io#10]
Από:
Το schoolmvn-1.0-SNAPSHOT.jar δεν είναι εκτελέσιμο, αλλά μπορούμε να το κάνουμε εκτελέσιμο χρησιμοποιώντας κάποιον από τους τρόπους που αναφέρονται [εδώ](https://www.baeldung.com/executable-jar-with-maven):

Είναι προτιμότερο:
Το schoolmvn-1.0-SNAPSHOT.jar δεν είναι εκτελέσιμο, αλλά μπορούμε να το κάνουμε εκτελέσιμο χρησιμοποιώντας κάποιον από τους [διάφορους τρόπους](https://www.baeldung.com/executable-jar-with-maven). Παρακάτω φαίνεται το pom.xml που χρησιμοποιεί τον τρόπο _maven-assembly-plugin_:

**Comment by jkost** [comment]
Διορθώθηκε. Ευχαριστώ.
