### ISSUE TITLE
6.7 Βελτίωση πρότασης jar-with-dependencies

### ISSUE THREAD

**Issue by skarmoutsosv** [jkost/jkost.github.io#11]
Από:
Αν ξαναχτίσετε το έργο, αυτή τη φορά θα δημιουργηθεί και το schoolmvn-1.0-SNAPSHOT-jar-with-dependencies.jar το οποίο περιέχει και όλα τα .jar αρχεία από τα οποία εξαρτάται:

Είναι προτιμότερο:
Αν ξαναχτίσετε το έργο, αυτή τη φορά θα δημιουργηθεί και το schoolmvn-1.0-SNAPSHOT-jar-with-dependencies.jar το οποίο περιέχει και όλα τα .jar αρχεία από τα οποία εξαρτάται. **Από τον αρχικό φάκελο του έργου, μπορούμε να το εκτελέσουμε με**:

$ java -jar **target**/schoolmvn-1.0-SNAPSHOT-jar-with-dependencies.jar

**Comment by jkost** [comment]
Διορθώθηκε. Ευχαριστώ.
