### ISSUE TITLE
Βελτίωση εμφάνισης άσκησης 1.6.6

### ISSUE THREAD

**Issue by skarmoutsosv** [jkost/jkost.github.io#4]
Στο 1.6, στην εκφώνηση της άσκησης 6 μπορεί να προστεθεί:
`Ο [τύπος του Ήρωνα](https://el.wikipedia.org/wiki/Τύπος_του_Ήρωνα) δίνει το εμβαδόν ενός τριγώνου συναρτήσει του μήκους των πλευρών του $$\large E=\sqrt{s(s-a)(s-b)(s-c)}$$ όπου s είναι η  ημιπερίμετρος του τριγώνου $$\Large s=\frac{a+b+c}{2}$$`

**Comment by jkost** [comment]
ευχαριστώ. Ενημερώθηκε.
