### ISSUE TITLE
Λανθασμένη επέκταση ονόματος αρχείων

### ISSUE THREAD

**Issue by skarmoutsosv** [jkost/jkost.github.io#5]
Στον φάκελο `Intro2ProgrammingWithJava/Week3/3.3-UML/assets/` υπάρχουν δύο αρχεία που έχουν λανθασμένη επέκταση ονόματος αρχείου.

Το Fig5.jpg έπρεπε να είναι Fig5.png
Το Fig7.jpg έπρεπε να είναι Fig7.png

```
$ file Fig5.jpg
Fig5.jpg: PNG image data, 401 x 527, 8-bit/color RGBA, non-interlaced

$ identify Fig5.jpg
Fig5.jpg PNG 401x527 401x527+0+0 8-bit sRGB 73232B 0.000u 0:00.000
```
Οπότε πρέπει να διορθωθούν και τα αντίστοιχα αρχεία .ipynb και .md που χρησιμοποιούν αυτές τις εικόνες.

**Comment by jkost** [comment]
καλημέρα.

Ευχαριστώ, ενημερώθηκαν, αν και οι browsers τις έδειχναν ΟΚ ακόμα και ως
jpg.

Γ.Κ.

**Comment by skarmoutsosv** [comment]
Επίσης δεν εμφανίζεται η εικόνα Fig8.png στο αρχείο .md

**Comment by jkost** [comment]
Διορθώθηκε κι αυτό. Ευχαριστώ.
