### ISSUE TITLE
Τυπογραφικό στο 6.7

### ISSUE THREAD

**Issue by skarmoutsosv** [jkost/jkost.github.io#7]
https://github.com/jkost/jkost.github.io/tree/master/Courses/Mathesis/Intro2ProgrammingWithJava/Week6/6.7-Exercise

- ...το κατάλληλο αρχείο **log4j**.xml
- ...παράμετρο περιβάλλοντος -Dlog4j.configurationFile=**log4j2**.xml

**Comment by jkost** [comment]
διορθώθηκε. Ευχαριστώ.
