### ISSUE TITLE
6.7 Βελτίωση πρότασης

### ISSUE THREAD

**Issue by skarmoutsosv** [jkost/jkost.github.io#8]
Δημιουργία έργου Maven

Στο τέλος του 4 πρέπει να προστεθεί: **Επίσης αντιγράψτε το αρχείο log4j2.xml στον αρχικό φάκελο του έργου.**

και στο 7 θα μπορούσε να προστεθεί:
Μπορείτε να το εκτελέσετε κατά τα γνωστά, **από τον αρχικό φάκελο του έργου,** π.χ.:

**Comment by jkost** [comment]
Έγινε. Ευχαριστώ.
