### ISSUE TITLE
6.7 Βελτίωση Run Maven -> Goals...

### ISSUE THREAD

**Issue by skarmoutsosv** [jkost/jkost.github.io#9]
Στην εγκατάστασή μου δεν είναι προεπιλεγμένο το Remember as, οπότε δεν εμφανιζόταν ως επιλογή Run Maven -> package
γι' αυτό προτείνω την παρακάτω τροποποίηση:

Μπορείτε να δημιουργήσετε κι άλλους στόχους (target) στο NetBeans ως εξής:
  1.  Δεξί κλικ στο έργο schoolmvn και επιλέξτε Run Maven -> Goals...
  2.  Γράψτε μέσα στο πεδίο Goals: package
  3. Επιλέξτε το **Remember as:**, πληκτρολογήστε **package** και πατήστε OK

**Comment by jkost** [comment]
διορθώθηκε, ευχαριστώ.
